class SimulationParams(object):
    PACKET_GENERATION_FINISH = 100
    PACKET_GENERATION_DELAY = 0
    BBU_DEBUG = False
    VIRTUAL_SWITCH_BITRATE = 1000
    EXTERNAL_TRANSMISSION_COFACTOR = 0.1
    INTERNAL_TRANSMISSION_COFACTOR = 0.01
