class SimulationParams(object):
    SIMULATION_TIME = 1000
    PACKET_GENERATION_FINISH = float('inf')
    PACKET_GENERATION_DELAY = 0
    BBU_DEBUG = False
    VIRTUAL_SWITCH_BITRATE = 90000
    VIRTUAL_SWITCH_QLIMIT = 10000
    EXTERNAL_TRANSMISSION_COFACTOR = 0.000001
    INTERNAL_TRANSMISSION_COFACTOR = 0.000001
